COQMAKEFILE ?= coq_makefile

.PHONY: all rocq extract demo test test-slow assumptions check clean
all: rocq

vendor/strictness-pcf/theories/Ty.v:
	@echo "vendor/strictness-pcf is missing; run: git submodule update --init" >&2
	@exit 1

Makefile.coq: _CoqProject
	$(COQMAKEFILE) -f _CoqProject -o $@

rocq: vendor/strictness-pcf/theories/Ty.v Makefile.coq
	$(MAKE) -f Makefile.coq

# The extracted checker: OCaml demonstrations and regression tests.
extract:
	$(MAKE) -C extraction extract

demo:
	$(MAKE) -C extraction run

test:
	$(MAKE) -C extraction test
	$(MAKE) -C reference test

# fact 4 = 24 through the PCF translation, about a minute.
test-slow:
	$(MAKE) -C extraction slow

# Every proved contract of theories/Contracts.v is closed under the global
# context: no axioms.
assumptions: rocq
	@mkdir -p checks
	@{ echo '(* Generated by make assumptions from theories/Contracts.v: the assumptions'; \
	   echo '   of every proved contract.  Not edited by hand. *)'; \
	   echo 'From DepTypes Require Import Contracts.'; \
	   sed -n 's/^Theorem \([A-Za-z0-9_]*_holds\).*/Print Assumptions \1./p' theories/Contracts.v; \
	 } > checks/Assumptions.v
	@out=$$(coqc -Q vendor/strictness-pcf/theories PCF -Q theories DepTypes checks/Assumptions.v); \
	  expected=$$(grep -c '^Print Assumptions' checks/Assumptions.v); \
	  closed=$$(echo "$$out" | grep -c 'Closed under the global context'); \
	  if [ "$$closed" -eq "$$expected" ]; then \
	    echo "assumptions: $$closed contracts closed under the global context"; \
	  else echo "$$out"; echo "assumptions: only $$closed of $$expected contracts are axiom-free"; exit 1; fi

check: rocq assumptions test

clean:
	@if test -f Makefile.coq; then $(MAKE) -f Makefile.coq clean; fi
	$(MAKE) -C extraction clean
	$(MAKE) -C reference clean
	rm -f Makefile.coq Makefile.coq.conf .Makefile.coq.d
	rm -rf checks
